version: '3'
services:
  # Redis for cache and pub/sub events to connected users
  redis:
    image: redis:4.0-alpine
    command: >
     --requirepass devpassword
  # All persistent user data and mission data is stored in PostgreSQL
  postgres:
    image: postgres:10.1-alpine
    ports:
      - 3332:5432
    environment:
      POSTGRES_PASSWORD: devpassword
      POSTGRES_USER: boris
      POSTGRES_DB: boris
  prod-verify:
    image: back-and-forth:latest
    depends_on:
      - redis
      - postgres
    ports:
      - 3333:3333  # The Backend server (HTTP)
    environment:
      NODE_ENV: production
