version: '3'
services:
  # Configuration used in development (docker-compose.yml) but not CI
  backend:
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend:ro
      - ./common:/app/common
      - ./tsconfig.json:/app/tsconfig.json
  frontend:
    volumes:
      - ./frontend:/app/frontend
      - ./common:/app/common
      - ./tsconfig.json:/app/tsconfig.json
