version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.16-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose -f docker-compose.yml -f docker-compose-ci.yml up -d
      # We can't mount from this container into docker, so copy the source files
      - run: docker cp ./backend/. repo_backend_1:/app/backend
      - run: docker cp ./common/. repo_backend_1:/app/common
      - run: docker cp ./frontend/. repo_frontend_1:/app/frontend
      - run: docker-compose exec frontend npm run build
      - run: docker-compose exec backend npm run lint
      - run: docker-compose exec backend npm run test
      - run: docker-compose down
workflows:
  version: 2
  test:
    jobs:
      - test
